### PR TITLE
Major edit to metadata creation

### PR DESCRIPTION
**Pull request by mlogie**
Metadata function edit to feed back a lot more data, allow previous metadata to be passed as an object, and combining the metadata creation into one function.

### CODE REVIEW

**Comment by 03rcooke** [comment]
@AugustT I can't understand the build fails?

**Comment by AugustT** [comment]
@03rcooke 

Travis log says 
```
Error: package or namespace load failed for ‘wrappeR’ in namespaceExport(ns, exports):
 undefined exports: extractMetadata
```

This means you are trying to export the function 'extractMetadata' but it doesn't exist.

You are exporting it here: https://github.com/BiologicalRecordsCentre/wrappeR/blob/c22ce2222908f85bfdbffa5fe95e8a93b9ed07dc/NAMESPACE#L9

But in Marks pull request he has deleted it, without removing the export line in the namespace file

@mlogie This suggests that you did not rebuild the package before putting the pull request. Rebuilding, or redocumenting, will re-generate the namespace file automatically (you should not edit the namespace file by hand), which would fix this issue. It will also rebuild the help documentation from the Roxygen tags which might need to be done after the changes you have made.

**Comment by mlogie** [comment]
Thanks @AugustT. I'm not sure how to rebuild the package - what's the command for that? I've not done that before.
I can't do it now, as my script and github repo is in the BRC project, and that project is currently inaccessible.

**Comment by AugustT** [comment]
In RStudio you can do Ctrl+Shift+B to build or Ctrl+Shift+D to document

**Comment by 03rcooke** [comment]
I've copied out the code from this pull request and built the package locally on my machine and then submitted as a separate pull request, which test out the changes and merge if working

**Pull request closed without merging**
