### PR TITLE
Allow reg_aggs through pipeline

### PR DESCRIPTION
**Pull request by 03rcooke**
Code to differentiate between regions (e.g., ENG) and region aggregates (e.g., GB) and allow both through the pipeline

### CODE REVIEW

**Comment by 03rcooke** [comment]
@AugustT is this build error to do with the changeover of web addresses for Travis?

**Comment by AugustT** [comment]
Its saying it cannot find the rmarkdown package which is odd. Normally I would restart the build but it wont let me... maybe they are starting to shut down .com? This is okay to merge as all the checks passed on the other site

**Comment by AugustT** [comment]
(assuming you added tests for the new functionality you added)

**Comment by AugustT** [comment]
I just commited directly to the main repo to fix the badges. Naughty, but i knew I could do it quickly without causing problems

**Pull request merged**
